import { Link } from 'react-router-dom'
import PageTitle from '../../components/page-title'

export default function TermsPage() {
  return(
    <div className="max-w-screen-lg mx-auto px-4 sm:px-6 py-8">
      <PageTitle title="Terms of Service" />
      <h1 className="font-bold text-2xl sm:text-4xl mb-14 text-center">Terms of Service</h1>

      <p className="mb-4">The Avenue website is owned and operated by Omari Tech (“Avenue,” “we,” “us” or “our”).</p>
      <p className="mb-4">These Terms of Use (these “Terms”) govern your access to and use of the website; including without limitation the purchase, sale, exchange, or modification of certain digital assets; our online and/or mobile services, and software provided on or in connection with those services (collectively, the “Service”).</p>
      <p className="mb-4">This Service also allows you to sell and purchase Crypto Assets (as defined below) via Sale, Auction and Buy it Now (“Sale”). You may only participate in the Sale by linking your digital wallets on supported bridge extensions such as MetaMask <a className="underline font-medium text-indigo-600" href="https://metamask.io/" target="_blank">https://metamask.io/</a>. MetaMask is an electronic wallet, which allows you to purchase, store, and engage in transactions using Ethereum & Binance Smart Chain cryptocurrency. Before putting up your unique digital asset for sale or putting in an offer to purchase a unique digital asset from another user, you will need to connect and unlock your digital wallets with that extension. Once you submit an order to sell or purchase a unique digital asset, your order is passed on to the applicable extension, which completes the transaction on your behalf.</p>
      <p className="mb-4">“Crypto Assets” refers to unique non-fungible tokens, implemented on the BSC & Ethereum blockchain (the “BSC & ETH Platform”) using smart contracts.</p>
      <p className="mb-4">ALL TRANSACTIONS INITIATED THROUGH OUR SERVICE ARE FACILITATED AND RUN BY THIRD-PARTY ELECTRONIC WALLET EXTENSIONS, AND BY USING OUR SERVICES YOU AGREE THAT YOU ARE GOVERNED BY THE TERMS OF SERVICE AND PRIVACY POLICY FOR THE APPLICABLE EXTENSIONS. FOR METAMASK, THOSE TERMS ARE AVAILABLE AT <a className="underline font-medium text-indigo-600" href="https://metamask.io/terms.html" target="_blank">https://metamask.io/terms.html</a> AND <a className="underline font-medium text-indigo-600" href="https://metamask.io/privacy.html" target="_blank">https://metamask.io/privacy.html</a>.</p>
      <p className="mb-4">THE AVENUE IS A PLATFORM. WE ARE NOT A BROKER, FINANCIAL INSTITUTION, OR CREDITOR. THE SERVICES ARE AN ADMINISTRATIVE PLATFORM ONLY. THE AVENUE FACILITATES TRANSACTIONS BETWEEN THE BUYER AND SELLER IN THE SALE BUT IS NOT A PARTY TO ANY AGREEMENT BETWEEN THE BUYER AND SELLER OF CRYPTO ASSETS OR BETWEEN ANY USERS.YOU BEAR FULL RESPONSIBILITY FOR VERIFYING THE IDENTITY, LEGITIMACY, AND AUTHENTICITY OF ASSETS YOU PURCHASE ON THE AVENUE. NOTWITHSTANDING INDICATORS AND MESSAGES THAT SUGGEST VERIFICATION, THE AVENUE MAKES NO CLAIMS ABOUT THE IDENTITY, LEGITIMACY, OR AUTHENTICITY OF ASSETS ON THE PLATFORM.</p>
      <p className="mb-4">Because we have a growing number of services, we sometimes need to describe additional terms for specific services. Those additional terms and conditions, which are available with the relevant services, then become part of your agreement with us if you use those services.</p>
      <p className="mb-4">THESE TERMS OF USE ARE IMPORTANT AND AFFECT YOUR LEGAL RIGHTS, SO PLEASE READ THEM CAREFULLY. WE WANT TO LET YOU KNOW THAT THE TERMS INCLUDE AN ARBITRATION AGREEMENT WHICH WILL, WITH LIMITED EXCEPTIONS, REQUIRE DISPUTES BETWEEN US TO BE SUBMITTED TO BINDING AND FINAL ARBITRATION. UNLESS YOU OPT OUT OF THE ARBITRATION AGREEMENT: (1) YOU WILL ONLY BE PERMITTED TO PURSUE CLAIMS AND SEEK RELIEF AGAINST US ON AN INDIVIDUAL BASIS, NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY CLASS OR REPRESENTATIVE ACTION OR PROCEEDING; AND (2) YOU ARE AGREEING TO MANDATORY INDIVIDUAL ARBITRATION FOR THE RESOLUTION OF DISPUTES AND WAIVING YOUR RIGHT TO A JURY TRIAL ON YOUR CLAIMS. PLEASE READ SECTION 15 CAREFULLY.BY CLICKING ON THE “I ACCEPT” BUTTON, COMPLETING THE ACCOUNT REGISTRATION PROCESS, USING OUR SERVICES AND/OR PURCHASING CRYPTO ASSETS, YOU AGREE TO BE BOUND BY THESE TERMS AND ALL OF THE TERMS INCORPORATED HEREIN BY REFERENCE. </p>
      <p className="mb-4">If you do not agree to these Terms, you may not access or use the Service or purchase the Crypto Assets.</p>
      <p className="mb-4">The Avenue reserves the right to change or modify these Terms at any time and in our sole discretion. If we make changes to these Terms, we will provide notice of such changes, such as by sending an email notification, providing notice through the Service or updating the “Last Updated” date at the beginning of these Terms. By continuing to access or use the Service, you confirm your acceptance of the revised Terms and all of the terms incorporated therein by reference. We encourage you to review the Terms frequently to ensure that you understand the terms and conditions that apply when you access or use the Service. If you do not agree to the revised Terms, you may not access or use the Service.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Privacy Policy</h3>
      <p className="mb-4">Please refer to our <Link as="a" to="/privacy-policy" className="underline font-medium text-indigo-600">Privacy Policy</Link> for information about how we collect, use and share personal information about you.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Account Registration and Communication Preferences</h3>
      <p className="mb-4">If you wish to participate in a Sale for Crypto Assets, you will need to register for an account on the Service (“Account”). By creating an Account, you agree to (a) provide accurate, current and complete Account information about yourself, (b) maintain and promptly update from time to time as necessary your Account information, (c) maintain the security of your password and accept all risks of unauthorized access to your Account and the information you provide to us, and (d) immediately notify us if you discover or otherwise suspect any security breaches related to the Service, or your Account. The Avenue will block multiple accounts of the same user. Also, you agree that you will not:</p>
      <ul className="list-disc list-inside pl-5 mb-6">
        <li className="mb-2">create another account if we’ve disabled one you had unless you have our written permission first;</li>
        <li className="mb-2">buy, sell, rent or lease access to your Account or username unless you have our written permission first;</li>
        <li className="mb-2">share your Account password with anyone; or</li>
        <li className="mb-2">log in or try to log in to access the Service through unauthorized third party applications or clients.</li>
        <li className="mb-2">The Avenue may require you to provide additional information and documents at the request of any competent authority or in case of application of any applicable law or regulation, including laws related to anti-laundering (legalization) of incomes obtained by criminal means, or for counteracting financing of terrorism. The Avenue may also require you to provide additional information and documents in cases where it has reasons to believe that:</li>
        <li className="mb-2">Your Account is being used for money laundering or for any other illegal activity;</li>
        <li className="mb-2">You have concealed or reported false identification information and other details; or</li>
        <li className="mb-2">Transactions effected via your Account were effected in breach of these Terms.</li>
      </ul>
      <p className="mb-4">In such cases, The Avenue, in its sole discretion, may pause or cancel your Sale transactions until such additional information and documents are reviewed by The Avenue and accepted as satisfying the requirements of applicable law. If you do not provide complete and accurate information and documents in response to such a request, The Avenue may refuse to provide the Content (defined in Section 4(A) below) to you.</p>
      <p className="mb-4">By creating an Account, you consent to receive electronic communications from The Avenue (e.g., via email or by posting notices to the Service). These communications may include notices about your Account (e.g., password changes and other transactional information) and are part of your relationship with us. You agree that any notices, agreements, disclosures or other communications that we send to you electronically will satisfy any legal communication requirements, including, but not limited to, that such communications be in writing. You should maintain copies of electronic communications from us by printing a paper copy or saving an electronic copy. We may also send you promotional communications via email, including, but not limited to, newsletters, special offers, surveys and other news and information we think will be of interest to you. You may opt out of receiving these promotional emails at any time by following the unsubscribe instructions provided therein.</p>
      <p className="mb-4">By submitting personal data through our Site or Services, you agree to the terms of our Privacy Policy and you expressly consent to the collection, use and disclosure of your personal data in accordance with the Privacy Policy.</p>
      <p className="mb-4">You must provide all equipment and software necessary to connect to the Service and services, including but not limited to, a mobile device that is suitable to connect with and use Service and services, in cases where the Service offers a mobile component. You are solely responsible for any fees, including Internet connection or mobile fees, that you incur when accessing the Service or services.</p>
      <p className="mb-4">Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by The Avenue or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components. For example, when you click to get more details about any of the Crypto Assets sold through our marketplace, you will notice a third party link to the website from which such Crypto Asset originated. Such website may include license terms governing the use of such Crypto Asset. In the event you purchase such Crypto Asset through our marketplace, you are required to comply with such terms.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Ownership</h3>
      <p className="mb-4">Unless otherwise indicated in writing by us, the Service and all content and other materials contained therein, including, without limitation, The Avenue logo and all designs, text, graphics, pictures, information, data, software, sound files, other files and the selection and arrangement thereof (collectively, “Content”) are the proprietary property of The Avenue or our affiliates, licensors or users, as applicable.</p>
      <p className="mb-4">Notwithstanding anything to the contrary in these Terms, the Service and Content may include software components provided by The Avenue or its affiliates or a third party that are subject to separate license terms, in which case those license terms will govern such software components.</p>
      <p className="mb-4">The Avenue logo and any of The Avenue product or service names, logos or slogans that may appear on the Service or Service are trademarks of The Avenue or our affiliates and may not be copied, imitated or used, in whole or in part, without our prior written permission. You may not use any metatags or other “hidden text” utilizing “The Avenue” or any other name, trademark or product or service name of The Avenue or our affiliates without our prior written permission. In addition, the look and feel of the Service and Content, including, without limitation, all page headers, custom graphics, button icons and scripts, constitute the service mark, trademark or trade dress of The Avenue and may not be copied, imitated or used, in whole or in part, without our prior written permission. All other trademarks, registered trademarks, product names and The Avenue names or logos mentioned on the Service are the property of their respective owners and may not be copied, imitated or used, in whole or in part, without the permission of the applicable trademark holder. Reference to any products, services, processes or other information by name, trademark, manufacturer, supplier or otherwise does not constitute or imply endorsement, sponsorship or recommendation by The Avenue.</p>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">License to Access and Use Our Service and Content</h3>
      <p className="mb-4">You are hereby granted a limited, nonexclusive, nontransferable, nonsublicensable, and personal license to access and use the Service and Content; provided, however, that such license is subject to these Terms and does not include any right to (a) sell, resell or use commercially the Service or Content, (b) distribute, publicly perform or publicly display any Content, (c) modify or otherwise make any derivative uses of the Service or Content, or any portion thereof, (d) use any data mining, robots or similar data gathering or extraction methods, (e) download (other than page caching) any portion of the Service or Content, except as expressly permitted by us, and (f) use the Service or Content other than for their intended purposes.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Hyperlinks</h3>
      <p className="mb-4">You are granted a limited, nonexclusive, nontransferable right to create a text hyperlink to the Service for noncommercial purposes, provided that such link does not portray The Avenue or our affiliates or any of our products or services in a false, misleading, derogatory or otherwise defamatory manner, and provided further that the linking site does not contain any adult or illegal material or any material that is offensive, harassing or otherwise objectionable. This limited right may be revoked at any time. You may not use a logo or other proprietary graphic of The Avenue to link to the Service or Content without our express written permission. Further, you may not use, frame or utilize framing techniques to enclose any of The Avenue trademark, logo or other proprietary information, including the images found on the Service, the content of any text or the layout or design of any page, or form contained on a page, on the Service without our express written consent.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Third Party Services</h3>
      <p className="mb-4">The Service may contain links to third-party websites (“Third-Party Websites”) and applications (“Third-Party Applications”). When you click on a link to a Third-Party Website or Third-Party Application, we will not warn you that you have left our Service and are subject to the Terms and conditions (including privacy policies) of another website or destination. Such Third-Party Websites and Third-Party Applications and are not under the control of The Avenue. The Avenue is not responsible for any Third-Party Websites or Third-Party Applications. The Avenue provides these Third-Party Websites and Third-Party Applications only as a convenience and does not review, approve, monitor, endorse, warrant, or make any representations with respect to Third-Party Websites or Third-Party Applications, or their products or services. You use all links in Third-Party Websites, and Third-Party Applications at your own risk. When you leave our Service, our Terms and policies no longer govern. You should review all applicable agreements and policies, including privacy and data gathering practices, of any Third-Party Websites or Third-Party Applications, and should make whatever investigation you feel necessary or appropriate before proceeding with any transaction with any third party.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">User Conduct</h3>
      <p className="mb-4">You agree that you will not violate any law, contract, intellectual property or other third party right, and that you are solely responsible for your conduct, while accessing or using the Service or participating in the Sale. You agree that you will abide by these Terms and will not:</p>
      <ul className="list-disc list-inside pl-5 mb-6">
        <li className="mb-2">Provide false or misleading information to The Avenue;</li>
        <li className="mb-2">Use or attempt to use another user’s Account without authorization from such user and The Avenue;</li>
        <li className="mb-2">Create or list counterfeit items;</li>
        <li className="mb-2">Pose as another person or create a misleading username;</li>
        <li className="mb-2">Use the Service in any manner that could interfere with, disrupt, negatively affect or inhibit other users from fully enjoying the Service, or that could damage, disable, overburden or impair the functioning of the Service in any manner;</li>
        <li className="mb-2">Develop, utilize, or disseminate any software, or interact with any API in any manner, that could damage, harm, or impair the Service;</li>
        <li className="mb-2">Reverse engineer any aspect of the Service, or do anything that might discover source code or bypass or circumvent measures employed to prevent or limit access to any Service, area or code of the Service;</li>
        <li className="mb-2">Attempt to circumvent any content-filtering techniques we employ, or attempt to access any feature or area of the Service that you are not authorized to access;</li>
        <li className="mb-2">Use any robot, spider, crawler, scraper, script, browser extension, offline reader or other automated means or interface not authorized by us to access the Service, extract data or otherwise interfere with or modify the rendering of Service pages or functionality;</li>
        <li className="mb-2">Use data collected from our Service to contact individuals, companies, or other persons or entities;</li>
        <li className="mb-2">Use data collected from our Service for any direct marketing activity (including without limitation, email marketing, SMS marketing, telemarketing, and direct marketing);</li>
        <li className="mb-2">Bypass or ignore instructions that control all automated access to the Service;</li>
        <li className="mb-2">Use the Service for any illegal or unauthorized purpose, or engage in, encourage or promote any activity that violates these Terms;</li>
        <li className="mb-2">Use the BSC & Ethereum Platforms to carry out any illegal activities, including but not limited to money laundering, terrorist financing or deliberately engaging in activities designed to adversely affect the performance of the Ethereum Platform, or the Service;</li>
        <li className="mb-2">Engage in wash trading or other deceptive or manipulative trading activities;</li>
        <li className="mb-2">Place misleading bids or offers;</li>
        <li className="mb-2">Spam listings for the purpose of causing a listing to appear at the top of the search results;</li>
        <li className="mb-2">Engage in behaviors that have the intention or the effect of artificially increasing view counts, favorites, volume, or other metrics that The Avenue might use to sort search results;</li>
        <li className="mb-2">Use the Service to carry out any financial activities subject to registration or licensing, including but not limited to creating, listing, or buying securities, commodities, options, real estate, or debt instruments;</li>
        <li className="mb-2">Use the Service from a country sanctioned by the government of the United States; or</li>
        <li className="mb-2">Use the Service to participate in fundraising for a business, protocol, or platform, including but not limited to creating, listing, or buying assets that are redeemable for financial instruments, assets that give owners rights to participate in an ICO or any securities offering, or assets that entitle owners to financial rewards, including but not limited to, DeFi yield bonuses, staking bonuses, and burn discounts.</li>
      </ul>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">User Information and Copyright</h3>
      <p className="mb-4">You are solely responsible for your use of the Services and for any User Information you provide, including compliance with applicable laws, rules, and regulations. We take no responsibility for the User Information posted or listed via the Services.You retain your rights to any User Information you submit, post, or display using the Services.By submitting, posting or displaying User Information on or through the Services, you grant us a worldwide, non-exclusive, sublicensable, royalty-free license to use, copy, modify, and display any text, content, files, communications, comments, feedback, suggestions, ideas, concepts, questions, data or other content that you submit or post on or through the Services or through tools or applications we provide for posting or sharing such content (collectively “User Information”) for our lawful business purposes, including to provide, promote, and improve the Services.</p>
      <p className="mb-4">The Avenue does not claim that submitting, posting or displaying User Information on or through the Services gives The Avenue any ownership or resale rights in your User Information. We're not saying we own it or will resell it. We're just saying we might show it off a bit.You represent and warrant that you have, or have obtained, all rights, licenses, consents, permissions, power and/or authority necessary to grant the rights granted herein for any User Information that you submit, post or display on or through the Services. You agree that such User Information will not contain material subject to copyright or other proprietary rights, unless you have necessary permission or are otherwise legally entitled to post the material and to grant The Avenue the license described above.The Avenue reserves the right to remove content without prior notice. The Avenue will take down works in response to formal infringement claims and will terminate a user's access to the Services if the user is determined to be a repeat infringer.If you believe that your content has been copied in a way that constitutes copyright infringement, please report this by contacting contactus@fomolab.io.Formal infringement claims regarding content on the Services must include:</p>
      <ul className="list-disc list-inside pl-5 mb-6">
        <li className="mb-2">A written communication delivered to the above;</li>
        <li className="mb-2">A physical or electronic signature of someone authorized to act on behalf of the copyright owner;</li>
        <li className="mb-2">Identification of the copyrighted work(s) allegedly infringed;</li>
        <li className="mb-2">Identification of material claimed to be infringing, reasonably sufficient to permit Company to locate the material;</li>
        <li className="mb-2">Information reasonably sufficient to permit Company to contact the complaining party. This can be an address, phone number, email address, or other suitable method of contact;</li>
        <li className="mb-2">A statement that the “complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent or the law; and”</li>
        <li className="mb-2">A statement that the information in the notice is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the copyright owner.</li>
        <li className="mb-2">If you believe that your likeness has been used in a way that violates your personality rights, please report this by contacting contactus@fomolab.io.Formal claims regarding content on the Services must include:</li>
        <li className="mb-2">A written communication delivered to the above;</li>
        <li className="mb-2">A physical or electronic signature of someone authorized to act on behalf of the person or the estate affected;</li>
        <li className="mb-2">Identification of material claimed to be violating, reasonably sufficient to permit Company to locate the material;</li>
        <li className="mb-2">Information reasonably sufficient to permit Company to contact the complaining party. This can be an address, phone number, email address, or other suitable method of contact;</li>
        <li className="mb-2">A statement that the “complaining party has a good faith belief that use of the material in the manner complained of is not authorized by the person or the estate affected, its agent or the law; and”</li>
        <li className="mb-2">A statement that the information in the notice is accurate and, under penalty of perjury, that the complaining party is authorized to act on behalf of the person or the estate.</li>
      </ul>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Indemnification</h3>
      <p className="mb-4">To the fullest extent permitted by applicable law, you agree to indemnify, defend and hold harmless The Avenue, and our respective past, present and future employees, officers, directors, contractors, consultants, equity holders, suppliers, vendors, service providers, parent companies, subsidiaries, affiliates, agents, representatives, predecessors, successors and assigns (individually and collectively, the “The Avenue Parties”), from and against all actual or alleged third party claims, damages, awards, judgments, losses, liabilities, obligations, penalties, interest, fees, expenses (including, without limitation, attorneys’ fees and expenses) and costs (including, without limitation, court costs, costs of settlement and costs of pursuing indemnification and insurance), of every kind and nature whatsoever, whether known or unknown, foreseen or unforeseen, matured or unmatured, or suspected or unsuspected, in law or equity, whether in tort, contract or otherwise (collectively, “Claims”), including, but not limited to, damages to property or personal injury, that are caused by, arise out of or are related to (a) your use or misuse of the Service, User Information or Crypto Assets, (b) any feedback you provide, (c) your violation of these Terms, and (d) your violation of the rights of a third party, including another user or MetaMask. You agree to promptly notify The Avenue of any third party Claims and cooperate with the The Avenue Parties in defending such Claims. You further agree that the The Avenue Parties shall have control of the defense or settlement of any third party Claims. THIS INDEMNITY IS IN ADDITION TO, AND NOT IN LIEU OF, ANY OTHER INDEMNITIES SET FORTH IN A WRITTEN AGREEMENT BETWEEN YOU AND THE AVENUE.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Disclaimers</h3>
      <p className="mb-4">EXCEPT AS EXPRESSLY PROVIDED TO THE CONTRARY IN A WRITING BY THE AVENUE, THE SERVICE, CONTENT CONTAINED THEREIN, AND CRYPTO ASSETS LISTED THEREIN ARE PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, EITHER EXPRESS OR IMPLIED. T THE AVENUE(AND ITS SUPPLIERS) MAKE NO WARRANTY THAT THE SERVICE:</p>
      <ul className="list-disc list-inside pl-5 mb-6">
        <li className="mb-2">(A) WILL MEET YOUR REQUIREMENTS; </li>
        <li className="mb-2">(B) WILL BE AVAILABLE ON AN UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE BASIS; OR </li>
        <li className="mb-2">(C) WILL BE ACCURATE, RELIABLE, COMPLETE, LEGAL, OR SAFE.</li>
      </ul>
      <p className="mb-4">THE AVENUE DISCLAIMS ALL OTHER WARRANTIES OR CONDITIONS, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, IMPLIED WARRANTIES OR CONDITIONS OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT AS TO THE SERVICE, CONTENT CONTAINED THEREIN. THE AVENUE DOES NOT REPRESENT OR WARRANT THAT CONTENT ON THE SERVICE IS ACCURATE, COMPLETE, RELIABLE, CURRENT OR ERROR-FREE. WE WILL NOT BE LIABLE FOR ANY LOSS OF ANY KIND FROM ANY ACTION TAKEN OR TAKEN IN RELIANCE ON MATERIAL OR INFORMATION, CONTAINED ON THE SERVICE. WHILE THE AVENUE ATTEMPTS TO MAKE YOUR ACCESS TO AND USE OF THE SERVICE AND CONTENT SAFE, THE AVENUE CANNOT AND DOES NOT REPRESENT OR WARRANT THAT THE SERVICE, CONTENT, ANY CRYPTO ASSETS LISTED ON OUR SERVICE OR OUR SERVERS ARE FREE OF VIRUSES OR OTHER HARMFUL COMPONENTS. WE CANNOT GUARANTEE THE SECURITY OF ANY DATA THAT YOU DISCLOSE ONLINE. YOU ACCEPT THE INHERENT SECURITY RISKS OF PROVIDING INFORMATION AND DEALING ONLINE OVER THE INTERNET AND WILL NOT HOLD US RESPONSIBLE FOR ANY BREACH OF SECURITY UNLESS IT IS DUE TO OUR GROSS NEGLIGENCE.WE WILL NOT BE RESPONSIBLE OR LIABLE TO YOU FOR ANY LOSS AND TAKE NO RESPONSIBILITY FOR, AND WILL NOT BE LIABLE TO YOU FOR, ANY USE OF CRYPTO ASSETS, INCLUDING BUT NOT LIMITED TO ANY LOSSES, DAMAGES OR CLAIMS ARISING FROM:</p>
      <ul className="list-disc list-inside pl-5 mb-6">
        <li className="mb-2">(A) USER ERROR SUCH AS FORGOTTEN PASSWORDS, INCORRECTLY CONSTRUCTED TRANSACTIONS, OR MISTYPED ADDRESSES; </li>
        <li className="mb-2">(B) SERVER FAILURE OR DATA LOSS; </li>
        <li className="mb-2">(C) CORRUPTED WALLET FILES; </li>
        <li className="mb-2">(D) UNAUTHORIZED ACCESS TO APPLICATIONS; </li>
        <li className="mb-2">(E) ANY UNAUTHORIZED THIRD PARTY ACTIVITIES, INCLUDING WITHOUT LIMITATION THE USE OF VIRUSES, PHISHING, BRUTEFORCING OR OTHER MEANS OF ATTACK AGAINST THE SERVICE OR CRYPTO ASSETS.</li>
      </ul>

      <p className="mb-4">CRYPTO ASSETS ARE INTANGIBLE DIGITAL ASSETS. THEY EXIST ONLY BY VIRTUE OF THE OWNERSHIP RECORD MAINTAINED IN THE BSC & ETHEREUM NETWORK. ANY TRANSFER OF TITLE THAT MIGHT OCCUR IN ANY UNIQUE DIGITAL ASSET OCCURS ON THE DECENTRALIZED LEDGER WITHIN THE BSC & ETHEREUM PLATFORM. WE DO NOT GUARANTEE THAT THE AVENUE OR ANY THE AVENUE PARTY CAN EFFECT THE TRANSFER OF TITLE OR RIGHT IN ANY CRYPTO ASSETS.The Avenue is not responsible for sustained casualties due to vulnerability or any kind of failure, abnormal behavior of software (e.g., wallet, smart contract), blockchains or any other features of the Crypto Assets. The Avenue is not responsible for casualties due to late report by developers or representatives (or no report at all) of any issues with the blockchain supporting Crypto Assets including forks, technical node issues or any other issues having fund losses as a result.Nothing in these Terms shall exclude or limit liability of either party for fraud, death or bodily injury caused by negligence, violation of laws, or any other activity that cannot be limited or excluded by legitimate means.</p>
      <p className="mb-4">SOME JURISDICTIONS DO NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES IN CONTRACTS WITH CONSUMERS, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Assumption of Risk</h3>
      <p className="mb-4">You accept and acknowledge:</p>
      <ul className="list-disc list-inside pl-5 mb-6">
        <li className="mb-2">The prices of blockchain assets are extremely volatile. Fluctuations in the price of other digital assets could materially and adversely affect the Crypto Assets, which may also be subject to significant price volatility. We cannot guarantee that any purchasers of Crypto Assets will not lose money.</li>
        <li className="mb-2">You are solely responsible for determining what, if any, taxes apply to your Crypto Assets transactions. Neither The Avenue nor any other The Avenue Party is responsible for determining the taxes that apply to Crypto Assets transactions.</li>
        <li className="mb-2">Our Service does not store, send, or receive Crypto Assets. This is because Crypto Assets exist only by virtue of the ownership record maintained on its supporting blockchain. Any transfer of Crypto Assets occurs within the supporting blockchain and not on this Service.</li>
        <li className="mb-2">There are risks associated with using an Internet based currency, including but not limited to, the risk of hardware, software and Internet connections, the risk of malicious software introduction, and the risk that third parties may obtain unauthorized access to information stored within your wallet. You accept and acknowledge that The Avenue will not be responsible for any communication failures, disruptions, errors, distortions or delays you may experience when using the Crypto Assets, however caused.</li>
        <li className="mb-2">A lack of use or public interest in the creation and development of distributed ecosystems could negatively impact the development of those ecosystems and related applications, and could therefore also negatively impact the potential utility or value of Crypto Assets.</li>
        <li className="mb-2">The regulatory regime governing blockchain technologies, cryptocurrencies, and tokens is uncertain, and new regulations or policies may materially adversely affect the development of the Sale and/or Service and the utility of Crypto Assets.</li>
        <li className="mb-2">The Service will rely on third-party platforms such as MetaMask to perform the transactions for the Sale of Crypto Assets. If we are unable to maintain a good relationship with such platform providers; if the terms and conditions or pricing of such platform providers change; if we violate or cannot comply with the terms and conditions of such platforms; or if any of such platforms loses market share or falls out of favor or is unavailable for a prolonged period of time, access to and use of the Service will suffer.</li>
        <li className="mb-2">There are risks associated with purchasing user generated content, including but not limited to, the risk of purchasing counterfeit assets, mislabeled assets, assets that are vulnerable to metadata decay, assets on smart contracts with bugs, and assets that may become untransferable. The Avenue reserves the right to hide collections, contracts, and assets affected by any of these issues or by other issues. Assets you purchase may become inaccessible on The Avenue. Under no circumstances shall the inability to view your assets on The Avenue serve as grounds for a claim against The Avenue.</li>
      </ul>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Limitation of Liability</h3>
      <p className="mb-4">TO THE FULLEST EXTENT PERMITTED BY LAW, IN NO EVENT WILL THE AVENUE BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOST PROFIT OR ANY INDIRECT, CONSEQUENTIAL, EXEMPLARY, INCIDENTAL, SPECIAL OR PUNITIVE DAMAGES ARISING FROM THESE TERMS, THE SERVICE, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS, OR FOR ANY DAMAGES RELATED TO LOSS OF REVENUE, LOSS OF PROFITS, LOSS OF BUSINESS OR ANTICIPATED SAVINGS, LOSS OF USE, LOSS OF GOODWILL, OR LOSS OF DATA, AND WHETHER CAUSED BY TORT (INCLUDING NEGLIGENCE), BREACH OF CONTRACT, OR OTHERWISE, EVEN IF FORESEEABLE AND EVEN IF THE AVENUE HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. ACCESS TO, AND USE OF, THE SERVICES, PRODUCTS OR THIRD PARTY SITES AND PRODUCTS ARE AT YOUR OWN DISCRETION AND RISK, AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR MOBILE DEVICE OR LOSS OF DATA RESULTING THEREFROM.NOTWITHSTANDING ANYTHING TO THE CONTRARY CONTAINED HEREIN, IN NO EVENT SHALL THE MAXIMUM AGGREGATE LIABILITY OF THE AVENUE ARISING OUT OF OR IN ANY WAY RELATED TO THESE TERMS, THE ACCESS TO AND USE OF THE SERVICE, CONTENT, CRYPTO ASSETS, OR ANY PRODUCTS OR SERVICES PURCHASED ON THE SERVICE EXCEED $50.THE FOREGOING LIMITATIONS OF LIABILITY SHALL NOT APPLY TO LIABILITY OF THE AVENUE FOR (A) DEATH OR PERSONAL INJURY CAUSED BY A MEMBER OF THE AVENUE’S NEGLIGENCE; OR FOR (B) ANY INJURY CAUSED BY A MEMBER OF THE AVENUE’S FRAUD OR FRAUDULENT MISREPRESENTATION.</p>
      <p className="mb-4">Some jurisdictions do not allow the exclusion or limitation of incidental or consequential damages, so the above limitation or exclusion may not apply to you. Some jurisdictions also limit disclaimers or limitations of liability for personal injury from consumer products, so this limitation may not apply to personal injury claims.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Modifications to the Service</h3>
      <p className="mb-4">We reserve the right in our sole discretion to modify, suspend or discontinue, temporarily or permanently, the Services (or any features or parts thereof) or suspend or discontinue the Sale at any time and without liability therefore.</p>
      
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Dispute Resolution</h3>
      <p className="mb-4">Please read the following arbitration agreement in this Section (“Arbitration Agreement”) carefully. It requires you to arbitrate disputes with The Avenue and limits the manner in which you can seek relief from us.</p>
      
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Applicability of Arbitration Agreement</h3>
      <p className="mb-4">You agree that any dispute or claim relating in any way to your access or use of the Service, to any products sold or distributed through the Service, or to any aspect of your relationship with The Avenue, will be resolved by binding arbitration, rather than in court, except that (1) you may assert claims in small claims court if your claims qualify; and (2) you or The Avenue may seek equitable relief in court for infringement or other misuse of intellectual property rights (such as trademarks, trade dress, domain names, trade secrets, copyrights, and patents).</p>
      
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Authority of Arbitrator</h3>
      <p className="mb-4">The arbitrator shall have exclusive authority to (a) determine the scope and enforceability of this Arbitration Agreement and (b) resolve any dispute related to the interpretation, applicability, enforceability or formation of this Arbitration Agreement including, but not limited to any claim that all or any part of this Arbitration Agreement is void or voidable. The arbitration will decide the rights and liabilities, if any, of you and The Avenue. The arbitration proceeding will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator shall have the authority to grant motions dispositive of all or part of any claim. The arbitrator shall have the authority to award monetary damages and to grant any non- monetary remedy or relief available to an individual under applicable law, the arbitral forum’s rules, and the Terms (including the Arbitration Agreement). The arbitrator shall issue a written award and statement of decision describing the essential findings and conclusions on which the award is based, including the calculation of any damages awarded. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and us.</p>
      
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Waiver of Jury Trial</h3>
      <p className="mb-4">YOU AND The Avenue HEREBY WAIVE ANY CONSTITUTIONAL AND STATUTORY RIGHTS TO SUE IN COURT AND HAVE A TRIAL IN FRONT OF A JUDGE OR A JURY. You and The Avenue are instead electing that all claims and disputes shall be resolved by arbitration under this Arbitration Agreement, except as specified in Section 15(b) above. An arbitrator can award on an individual basis the same damages and relief as a court and must follow these Terms as a court would. However, there is no judge or jury in arbitration, and court review of an arbitration award is subject to very limited review.</p>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Waiver of Class or Other Non-Individualized Relief</h3>
      <p className="mb-4">ALL CLAIMS AND DISPUTES WITHIN THE SCOPE OF THIS ARBITRATION AGREEMENT MUST BE ARBITRATED ON AN INDIVIDUAL BASIS AND NOT ON A OR COLLECTIVE CLASS BASIS, ONLY INDIVIDUAL RELIEF IS AVAILABLE, AND CLAIMS OF MORE THAN ONE CUSTOMER OR USER CANNOT BE ARBITRATED OR CONSOLIDATED WITH THOSE OF ANY OTHER CUSTOMER OR USER. If a decision is issued stating that applicable law precludes enforcement of any part of this subsection’s limitations as to a given claim for relief, then that claim must be severed from the arbitration and brought in the state or federal courts located in the the United Arab Emirates. All other claims shall be arbitrated.</p>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">30-Day Right to Opt Out</h3>
      <p className="mb-4">You have the right to opt out of the provisions of this Arbitration Agreement by sending written notice of your decision to opt out to the following address: contactus@fomolab.io, within 30 days after first becoming subject to this Arbitration Agreement. Your notice must include your name and address, the email address you used to set up your account (if you have one), and an unequivocal statement that you want to opt out of this Arbitration Agreement. If you opt out of this Arbitration Agreement, all other parts of these Terms will continue to apply to you. Opting out of this Arbitration Agreement has no effect on any other arbitration agreements that you may currently have, or may enter in the future, with us.</p>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Severability</h3>
      <p className="mb-4">Except as provided in this Section, if any part or parts of this Arbitration Agreement are found under the law to be invalid or unenforceable, then such specific part or parts shall be of no force and effect and shall be severed and the remainder of the Arbitration Agreement shall continue in full force and effect.</p>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Survival of Agreement</h3>
      <p className="mb-4">This Arbitration Agreement will survive the termination of your relationship with The Avenue.</p>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Modification</h3>
      <p className="mb-4">Notwithstanding any provision in these Terms to the contrary, we agree that if The Avenue makes any future material change to this Arbitration Agreement, you may reject that change within thirty (30) days of such change becoming effective by writing to The Avenue at the following address: contactus@fomolab.io.</p>

      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Governing Law and Venue</h3>
      <p className="mb-4">These Terms, your access to and use of the Service and Content, and your participation in the Sale shall be governed by and construed and enforced in accordance with the laws of the United Arab Emirates, without regard to conflict of law rules or principles of the United Arab Emirates, or any other jurisdiction) that would cause the application of the laws of any other jurisdiction that would cause the application of the laws of any other jurisdiction. Any dispute between the parties that is not subject to arbitration or cannot be heard in small claims court, shall be resolved in the state or federal courts of Dubai in the United Arab Emirates.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Termination</h3>
      <p className="mb-4">Notwithstanding anything contained in these Terms, we reserve the right, without notice and in our sole discretion, to terminate your right to access or use the Service at any time and for any or no reason, and you acknowledge and agree that we shall have no liability or obligation to you in such event and that you will not be entitled to a refund of any amounts that you have already paid to us, to the fullest extent permitted by applicable law.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Severability</h3>
      <p className="mb-4">If any term, clause or provision of these Terms is held invalid or unenforceable, then that term, clause or provision will be severable from these Terms and will not affect the validity or enforceability of any remaining part of that term, clause or provision, or any other term, clause or provision of these Terms.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Survival</h3>
      <p className="mb-4">The following sections will survive the expiration or termination of these Terms and the termination of your Account: all defined terms and Sections 1-4 and 7-19.</p>
      <h3 class="pt-8 pb-2 font-bold text-xl sm:text-2xl">Miscellaneous</h3>
      <p className="mb-4">These Terms along with the Sale Rules constitute the entire agreement between you and The Avenue relating to your access to and use of the Services and Content, and your participation in the Sale. These Terms, and any rights and licenses granted hereunder, may not be transferred or assigned by you without the prior written consent of The Avenue prior, concurrent or subsequent circumstance, and The Avenue’s failure to assert any right or provision under these Terms shall not constitute a waiver of such right or provision. Except as otherwise provided herein, these Terms is intended solely for the benefit of the parties and are not intended to confer third party beneficiary rights upon any other person or entity.</p>

    </div>
  )
}