name: IONOS.space

on: [push]

jobs:
  ionos-space:
    runs-on: ubuntu-latest
    steps:
      - name: Get Ionos Project data
        uses: ionos-deploy-now/retrieve-project-info-action@v1
        id: project
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          project: 87382ee9-6659-4baa-9213-a5c1002c9031
          service-host: api-eu.ionos.space
      - name: checkout
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Node.js 12.16.x
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.16.x
      - name: Prepare Project build environment
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: |
          npm install --global yarn
          yarn install --frozen-lockfile
      - name: Build Node project
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        run: yarn build
        env:
          CI: false
          SITE_URL: ${{ steps.project.outputs.site-url }}
      - name: Deploy to IONOS
        if: ${{ steps.project.outputs.deployment-enabled == 'true' }}
        uses: ionos-deploy-now/deploy-to-ionos-action@v1
        with:
          branch-id: ${{ steps.project.outputs.branch-id }}
          service-host: api-eu.ionos.space
          api-key: ${{ secrets.IONOS_API_KEY }}
          remote-host: ${{ steps.project.outputs.remote-host }}
          dist-folder: build
          project: 87382ee9-6659-4baa-9213-a5c1002c9031
          storage-quota: ${{ steps.project.outputs.storage-quota }}
